### ISSUE TITLE
拉钩api更新了：totalPageCount字段不存在＋result所在的层级也发生了变化

### ISSUE THREAD

**Issue by jhong123** [LiZhenNet/GetJobsFromLagou#2]
1.jobjson.content.result >> jobjson.content.positionResult.result

2.自己计算totalPageCount：
var totalPageCount=Math.ceil(jobjson.content.positionResult.totalCount/15)
if (pageNo<totalPageCount) {...}

跑出数据来了，图表显示ok，感谢🙏

**Comment by LiZhenNet** [comment]
没事，自己也是写来练习的，周末有时间更新一下。
